name: Run Container

on:
  workflow_dispatch:

jobs:
  run-containers:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: superuser
          MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
        options: >-
          --mount type=bind,source=${{ github.workspace }}/solar-dump,target=/tmp/solar-dump

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Mongo to be ready
        run: |
          until docker exec mongo mongo --eval "print('Mongo is ready')" 2>/dev/null; do
            echo "Waiting for MongoDB to be available..."
            sleep 5
          done

      - name: Export environment variables
        run: |
          echo "MONGO_URI=mongodb://superuser:mysecretpassword@localhost:27017/superData" >> $GITHUB_ENV
          echo "MONGO_USERNAME=superuser" >> $GITHUB_ENV
          echo "MONGO_PASSWORD=mysecretpassword" >> $GITHUB_ENV

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - run: npm install

      - name: Run unit tests
        run: npm test

      - name: Run code coverage
        run: npm run coverage

      - name: Start application
        run: |
          npm start &
          sleep 10 

      - name: Hit POST request to localhost
        run: |
          curl -X POST 'http://localhost:3000/planet' \
          -H 'Content-type: application/json; charset=UTF-8' \
          --data-raw '{"id":"3"}'

      - name: Verify app is running
        run: curl http://localhost:3000/

      - name: Build Docker Image
        run: docker build -t solar-project .

      - name: Run Docker Container
        run: |
          docker run -d \
          --env MONGO_URI=$MONGO_URI \
          --env MONGO_USERNAME=$MONGO_USERNAME \
          --env MONGO_PASSWORD=$MONGO_PASSWORD \
          -p 3000:3000 \
          --name solar-app \
          solar-project:latest

      - name: Test Docker Container API
        run: |
          sleep 10
          curl http://localhost:3000/
